export const ProfileActionTypes = {
    SET_VIEWING_PROFILE: 'profile/SET_VIEWING_PROFILE',
    SET_LOADING_PROFILE: 'profile/SET_LOADING_PROFILE',
    SET_PROFILE_USER: 'profile/SET_PROFILE_USER',
    SET_PROFILE_FOLLOWING: 'profile/SET_PROFILE_FOLLOWING',
    SET_PROFILE_CLUBS: 'profile/SET_PROFILE_CLUBS'
}